<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Stalwart.MailParser.Port.Tests</AssemblyName>
    <RootNamespace>Stalwart.MailParser.Port</RootNamespace>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(DefineConstants);STALWART_PORT_TESTS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\src\**\*.cs" Exclude="..\src\obj\**;..\src\bin\**" />
    <Compile Include="integration_test.cs" />
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\resources\**\*">
      <Link>resources\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
